django_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movies.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("<int:pk>/", views.MovieDetailView.as_view())
]

movies/models.py
from django.db import models
from datetime import date


class Category(models.Model):
    """ Categories"""
    name = models.CharField("Category", max_length=150)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Actor(models.Model):
    """Actors"""
    name = models.CharField("Name", max_length=100)
    age = models.PositiveSmallIntegerField("Age", default=0)
    description = models.TextField("Description")
    image = models.ImageField("Pictures", upload_to="actors/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actors and director"
        verbose_name_plural = "Actors and director"


class Genre(models.Model):
    """Genre"""
    name = models.CharField("Category", max_length=100)
    description = models.TextField("Description")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Genre"
        verbose_name_plural = "Genres"


class Movie(models.Model):
    """Movies"""
    title = models.CharField("Title", max_length=100)
    tagLine = models.CharField("Tag", max_length=100, default='')
    description = models.TextField("Description")
    poster = models.ImageField("Poster", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Release date", default=2019)
    country = models.CharField("Country", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="director", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="actors", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="genres")
    world_premiere = models.DateField("Premiere in world", default=date.today)
    budget = models.PositiveIntegerField("Budget", default=0, help_text="sum in dollars")
    fees_in_usa = models.PositiveIntegerField("Fees USA", default=0, help_text="sum in dollars")
    fees_in_world = models.PositiveIntegerField("Fees in World", default=0, help_text="sum in dollars")
    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Draft", default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"


class MovieShots(models.Model):
    """Screenshot from movie"""
    title = models.CharField("Title", max_length=100)
    description = models.TextField("Description")
    image = models.ImageField("Pictures", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Movie", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Shot from movie"
        verbose_name_plural = "Shots from movie"


class RatingStar(models.Model):
    """Star rating"""
    value = models.PositiveSmallIntegerField("Value", default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = "Star rating"
        verbose_name_plural = "Stars rating"


class Rating(models.Model):
    """Rating"""
    ip = models.CharField("IP address", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="star")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="movie")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Rating"
        verbose_name_plural = "Ratings"


class Reviews(models.Model):
    """Reviews"""
    email = models.EmailField()
    name = models.CharField("Name", max_length=100)
    text = models.TextField("Message", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Parent", on_delete=models.SET_NULL, blank=True, null=True)
    movie  = models.ForeignKey(Movie, verbose_name="movie", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

movies/views.py
from django.shortcuts import render
from django.views.generic.base import View

from .models import Movie


class MoviesView(View):
    """List of movie"""

    def get(self, request):
        movies = Movie.objects.all()
        return render(request, "movies/movies.html", {"movie_list": movies})


class MovieDetailView(View):
    """Full describes of movie"""
    def get(self, request, pk):
        movie = Movie.objects.get(id=pk)
        return render(request, "movies/movie_detail.html", {"movie": movie})

templates/base.html
<!DOCTYPE html>
{% load static recaptcha3 %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->

      {% recaptcha_init %}
      {% recaptcha_ready action_name='homepage' %}
</head>
<body>
<div id="page" class="page">
    <div class="main-banner bg {% block header %}  {% endblock header %}" id="home">
        {% include 'include/header.html' %}
    </div>
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
            <a href="index.html" class="editContent">Home</a>
        </li>
        <li class="breadcrumb-item active editContent">Single Page</li>
    </ol>
    {% block content %}

    {% endblock content %}
    {% include 'include/footer.html' %}
</div>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="http://twitter.github.com/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>
</body>
</html>

templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static i18n %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>{% trans 'Год' %}:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Страна' %}:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Слоган' %}:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>{% trans 'Режиссер' %}:</b>
                            {% for director in movie.directors.all %}
                                <a href="{{ director.get_absolute_url }}">
                                    {{ director.name }}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>{% trans 'Актеры' %}:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{{ actor.get_absolute_url }}">
                                    {{ actor.name }}
                            </a>
                        {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none"><span><b>{% trans 'Жанр' %}:</b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                                    </span>
                    </li>
                    <li>
                        <span><b>{% trans 'Премьера в мире' %}:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li>
                        <span><b>{% trans 'Бюджет' %}:</b> ${{ movie.budget }}</span></li>
                    <li>
                        <span><b>{% trans 'Сборы в США' %}:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li>
                        <span><b>{% trans 'Сборы в мире' %}:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>{% trans 'Рейтинг' %}:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">4.0</span>
                        </form>
                    </li>
                </ul>

                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-facebook-f"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent">
                                    <span class="fa fa-twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                    <span class="fa fa-vk"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                {% trans 'О фильме'  %} {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots "
                         alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent">
                {{ movie.description|safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ movie.reviews_set.count }}</span>
                        {% trans 'Оставить отзыв ' %}
                    </h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4"
                          id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            {{ form.text }}
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                {{ form.name }}
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                {{ form.email }}
                            </div>
                            {{ form.captcha }}
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te2.jpg' %}" class="img-fluid "
                                     alt="image">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }

    </script>
{% endblock movie %}

templates/movies/movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for movie in movie_list %}
    {{ movie.title }}
{% endfor %}
</body>
</html>